### ISSUE TITLE
Перезагрузки роутера

### ISSUE THREAD

**Issue by RADon0880** [nikrays/Zapret-on-Keenetic#2]
Добрый день! Спасибо за инструкцию. У меня Keenetic Giga 1010. Послу установки по инструкции доступ к сайтам на всех устройствах появился. Однако роутер стал случайным образом перезагружаться. Есть подозрение, что это происходит, когда одно или несколько устройств проигрывают видео с YouTube. Но это не точно. Есть ли идеи, куда копать, чтобы устранить эту проблему?

**Comment by nikrays** [comment]
@RADon0880 
https://github.com/bol-van/zapret/issues/311
https://github.com/bol-van/zapret/issues/306
