### ISSUE TITLE
Не работает YouTube на телевизорах WebOS

### ISSUE THREAD

**Issue by segadrozdik** [nikrays/Zapret-on-Keenetic#4]
Не работает приложение Ютуб на телевизорах LG WebOS на всех стадиях проекта Zapret-on-Keenetic/
Две недели, на компе и на смартфонах работает без нареканий. Все установлено строго по инструкциям

**Comment by nikrays** [comment]
@segadrozdik дот настраивали? Что за провайдер

**Comment by segadrozdik** [comment]
> @segadrozdik дот настраивали? Что за провайдер

Да, все по инструкции. Есть один ньюанс - отключаю тв от сети Кенетик - запускаю через раздачу Wi-Fi со смартфона - YouTube стартует, далее возврат на Keenetic и работает. Но при выкл вкл тв приложение не стартует, бесконечная попытка открыть интерфейс (главную страницу ютуба)

**Comment by nikrays** [comment]
Попробуйте сменить строку в конфиге, на [эту](https://github.com/nikrays/Zapret-on-Keenetic?tab=readme-ov-file#%D0%BD%D0%B8%D0%B6%D0%B5-%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

**Comment by segadrozdik** [comment]
> Попробуйте сменить строку в конфиге, на [эту](https://github.com/nikrays/Zapret-on-Keenetic?tab=readme-ov-file#%D0%BD%D0%B8%D0%B6%D0%B5-%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

Не помогло, будем ковырятся дальше

**Comment by segadrozdik** [comment]
> > Попробуйте сменить строку в конфиге, на [эту](https://github.com/nikrays/Zapret-on-Keenetic?tab=readme-ov-file#%D0%BD%D0%B8%D0%B6%D0%B5-%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)
> 
> Не помогло, будем ковырятся дальше

Заработало, обновил Zapret через команду внизу и конфиг второй

**Comment by nikrays** [comment]
@segadrozdik всё-таки второй конфиг, хорошо, а команда самая последняя в инструкции? которая обновляет весь репозиторий

**Comment by cherrypashka47** [comment]
та же самая проблема, но, к сожалению, ни ваш способ, ни смена строки не помогли( на других устройствах всё летает

**Comment by nikrays** [comment]
> та же самая проблема, но, к сожалению, ни ваш способ, ни смена строки не помогли( на других устройствах всё летает

Все способы хороши, я думаю вы найдете ключ к успеху

**Comment by segadrozdik** [comment]
> Попробуйте сменить строку в конфиге, на [эту](https://github.com/nikrays/Zapret-on-Keenetic?tab=readme-ov-file#%D0%BD%D0%B8%D0%B6%D0%B5-%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

Опять не работает, правда репозиторий стоит на встроенной памяти, если это имеет значение

**Comment by nikrays** [comment]
> > Попробуйте сменить строку в конфиге, на [эту](https://github.com/nikrays/Zapret-on-Keenetic?tab=readme-ov-file#%D0%BD%D0%B8%D0%B6%D0%B5-%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)
> 
> Опять не работает, правда репозиторий стоит на встроенной памяти, если это имеет значение

Хз, я убрал у себя из инструкции, способ установки на внутреннюю память, а то мостом будут ещё мне писать, что "делал по этой инструкции и роутер вообще перестал работать". Поэтому нанд не хочу, только на флэшку

**Comment by segadrozdik** [comment]
на моб интернете Мегафон работает на альтернативном конфиге (соц сеть i), ютуб работает везде кроме ТВ LG webOS. В принципе пока все устраивает, но непонятно почему webos не пропускает ютуб

**Comment by nikrays** [comment]
> на моб интернете Мегафон работает на альтернативном конфиге (соц сеть i), ютуб работает везде кроме ТВ LG webOS. В принципе пока все устраивает, но непонятно почему webos не пропускает ютуб

Попробуйте выключить все сетевое оборудование на минуту и включите потом, а также приведите настройки днс к такому виду как на скриншоте в разделе подготовка

**Comment by Andy-Foxxx** [comment]
Та же проблема на телевизоре Samsung (Tizen), вчера всё работало, сегодня только на компах и телефонах пашет, выкл/вкл  на пол часа ничего не дали, да и с чего дадут то?

**Comment by nikrays** [comment]
Странно все это, я ни у себя ни у тех кому лично настраивал, такого не наблюдал, это очень странно, надо проверить все ли сделано в соответствии, отключен ли ipv6, установлены ли все компоненты, точно ли исполнены все скрипты

**Comment by segadrozdik** [comment]
ip6 должен быть отключён??? 😱😱😱😱

**Comment by nikrays** [comment]
Не в компонентах а в настройках ethernet

**Comment by segadrozdik** [comment]
> Не в компонентах а в настройках ethernet

В настройках тв или в роутере нужно отключить ip6?

**Comment by nikrays** [comment]
И там и там

**Comment by segadrozdik** [comment]
Пробую

**Comment by Andy-Foxxx** [comment]
Переключил на роутере в ethernet - IPv6 с "Автоматически" на "Не используется", переподключился, в телевизоре вообще нет IPv6, только IPv4, после включения ютуба на ТВ после заставки с минуту висит чёрный экран, затем ошибка: "Произошла ошибка сети"

**Comment by segadrozdik** [comment]
У меня тоже так и не работает, выкл ip6 в тв и на кенетике, попытка запуска и висит, оператор мегафон через модем, плата крокс по Ethernet в роутер

**Comment by nikrays** [comment]
Не мотивировано
